### PR TITLE
coreos-install: Add a sync point before mounting

### PR DESCRIPTION
**Pull request by dm0-**
This is a follow-up to #242.  It waits five minutes before giving up.

### CODE REVIEW

**Comment by bgilbert** [comment]
If I force a signature check failure, I get:
```
gpg: Can't check signature: No public key
2: GPG signature verification failed for coreos_production_image.bin.bz2
Error: return code 1 from exit 1
/dev/sda: 8 bytes were erased at offset 0x00000200 (gpt): 45 46 49 20 50 41 52 54
/dev/sda: 2 bytes were erased at offset 0x000001fe (PMBR): 55 aa
/dev/sda: calling ioctl to re-read partition table: Success
core@coreos_production_pxe-1451-0-0-2 ~ $ ./coreos-install: line 388: /tmp/coreos-install.C4jBLOrDvT/disk_modified: No such file or directory

core@coreos_production_pxe-1451-0-0-2 ~ $ 
```

If I force the `blockdev --rereadpt` loop to fail, I get:

```
gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" [ultimate]
```

and then the process hangs forever.

**Comment by dm0-** [comment]
The first case sounds correct.  We can silence the last line, if that's what you're concerned about.

Are you sure it wasn't waiting for the timeout in the second case?  I don't see what would hang forever.

**Comment by bgilbert** [comment]
1. Yeah, the last line was my point.

2. It's still hung in my test VM.  😃

**Comment by dm0-** [comment]
Okay, opening the pipe was blocking, so the timeout value didn't matter.  Should be fixed now.

**Comment by dm0-** [comment]
I've added a line of output.

**Pull request merged**
