### PR TITLE
systemd: add a service to clean old rootfs files

### PR DESCRIPTION
**Pull request by dm0-**

### CODE REVIEW

**Comment by crawford** [comment]
Why not do this in the update-engine postinst instead?

**Comment by dm0-** [comment]
Mostly because I didn't know it existed.  I'll try to move this to update_engine instead.
/cc @marineam

**Comment by marineam** [comment]
Because the time postinst runs has nothing to do with if/when the system
actually boots to the new /usr which is when that symlink breaks and
becomes invalid.

Also modifying the running system fs is somewhat counter to the whole
atomic update concept. For all we know the older version needs that symlink
to avoid something exploding. It is only the new version that is shipping
without a default config file.

**Comment by marineam** [comment]
No please don't put this in update_engine. This service will more reliably
do the right thing.

**Comment by dm0-** [comment]
Okay, reopening this.

**Comment by marineam** [comment]
LGTM

**Comment by crawford** [comment]
@marineam ah, that makes sense.

LGTM

**Comment by dm0-** [comment]
This is unneeded for the time being.

**Pull request closed without merging**
