### PR TITLE
extend-filesystems script: fix raid device name when using HP Smart Array CCISS driver

### PR DESCRIPTION
**Pull request by andrejbaran**
Hi,

this should fix coreos/bugs#1037.
It's kind of a "hotfix" so if there's a proper way of fixing this let me know.

Thanks!

### CODE REVIEW

**Comment by marineam** [comment]
Hm, maybe just use tr to convert any ! to / instead of being specific to cciss. Why on earth does lsblk use ! ...

**Comment by andrejbaran** [comment]
I honestly have no idea what's with the ! but my guess is the cciss driver is the one to blame here.
I'm not sure using tr is a safe option since (and I know this seems unlikely) what if there is ! in the mount point path.

Only the device name should be changed so how about this:
```
sed -e 's/NAME="\([^!]*\)!\([^"]*\)"/NAME="\1\/\2"/'
```

**Comment by andrejbaran** [comment]
Actually, since bash is being used here, how about this:
```
eval "$dev_info"
NAME=${NAME//\!//}
```

[substring replacement in bash](http://tldp.org/LDP/abs/html/string-manipulation.html#SUBSTRREPL00)

**Comment by vcaputo** [comment]
Unless someone can show me something saying `!` is the accepted way of representing a `/` in a device name, I'm inclined to limit this substitution to just `s/^cciss\!/cciss\//`

**Comment by marineam** [comment]
I'm taking a quick look to see where the ! came from now.

**Comment by marineam** [comment]
Looks like a standard thing. From `device_get_devnode`

```c
        /* return name without allocation, tmp == NULL */
        if (strchr(dev_name(dev), '!') == NULL)
                return dev_name(dev);

        /* replace '!' in the name with '/' */
        *tmp = kstrdup(dev_name(dev), GFP_KERNEL);
        if (!*tmp)
                return NULL;
        while ((s = strchr(*tmp, '!')))
                s[0] = '/';
        return *tmp;
```

**Comment by marineam** [comment]
https://github.com/coreos/linux/blob/master/drivers/base/core.c#L1331

**Comment by marineam** [comment]
LGTM, thanks!

**Comment by andrejbaran** [comment]
Thanks!

**Pull request merged**
